[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["engine"]
include-package-data = false

[project]
name = "microenginewebhookspy"
version = "2.0.0"
description = "Exemplar microengine in python using webhooks"
readme = "README.md"
authors = [
    {name = "PolySwarm Developers", email = "info@polyswarm.io"},
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.10,<4"
dependencies = [
    "polyswarm_engine>=3.0.4",
    "celery",
    "requests",
    "urllib3>=2.0",
]
license = "MIT"

[project.urls]
Homepage = "https://github.com/polyswarm/microengine-webhooks-py"

[project.optional-dependencies]
tests = [
    "pytest",
    "pytest-mock",
    "requests-mock",
]
web = [
    "flask",
    "itsdangerous",
]
gunicorn = [
    "gunicorn",
]

[tool.flake8]
max-line-length = "120"
exclude = "test"

[tool.yapf]
column_limit = "120"
based_on_style = "pep8"
align_closing_bracket_with_visual_indent = "true"
coalesce_brackets = "true"
# dedent_closing_brackets = "true"
# indent_dictionary_value = "true"
# split_before_dot = "true"
