[project]
name = "microenginewebhookspy"
version = "1.0.0"
description = "Exemplar microengine in python using webhooks"
readme = "README.md"
authors = [
    {name = "PolySwarm Developers", email = "info@polyswarm.io"},
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.10,<4"
dependencies = [
    "psengine>=2.4.6",
    "celery",
    "requests",
    "urllib3>=2.0",
]
license = "MIT"

[project.urls]
Homepage = "https://github.com/polyswarm/microengine-webhooks-py"

[project.optional-dependencies]
tests = [
    "pytest",
    "pytest-mock",
    "requests-mock",
]
http = [
    "itsdangerous",
]
gunicorn = [
    "gunicorn",
]
