apiVersion: v1
kind: Service
metadata:
  name: {{ include "microengine-webhooks-py.fullname" . }}-nginx
  labels:
    {{- include "microengine-webhooks-py.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "microengine-webhooks-py.selectorLabels" . | nindent 4 }}
