{{- if .Values.nginx.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microengine-webhooks-py.worker.serviceAccountName" . }}
  labels:
    {{- include "microengine-webhooks-py.labels" . | nindent 4 }}
  {{- with .Values.worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
