version: '3.7'

services:
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
    networks:
      - microengine-webhooks
  celery:
    build:
      context: ../
      dockerfile: docker/worker.Dockerfile
    networks:
      - microengine-webhooks
    environment:
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=pyamqp://user:guest@rabbitmq//
      - PROCESS_TYPE=celery
  integration:
    build:
      context: ../
      dockerfile: docker/worker.Dockerfile
    ports:
      - "5000:5000"
    networks:
      - microengine-webhooks
      - default
    environment:
      - PYTHONUNBUFFERED=1
      - WEBHOOK_SECRET=qwertyuiop
      - WEBHOOK_URL=http://microengine-webhooks:8080/
      - PROCESS_TYPE=integration
  microengine-webhooks:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - microengine-webhooks
    environment:
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=pyamqp://user:guest@rabbitmq//
      - WEBHOOK_SECRET=qwertyuiop
      - LOG_LEVEL=DEBUG
      - LOG_FORMAT=text

networks:
  microengine-webhooks:
    driver: bridge
